### ISSUE TITLE
Write Tests for everything!

### ISSUE THREAD

**Issue by rohansaw** [hpi-swa-teaching/TelegramClient#108]
**Is your feature request related to a problem? Please describe.**
We want to work with the XP-Workflow. Everything should be tested before even implementing it.
Now we should write Tests for the code so far.

**Describe the solution you'd like**
Write test for all the code existing so far.

- Not sure wether tests should use a Mock-Object or the real tdlib-calls

**Comment by schmidtjonas** [comment]
We should use the Mock-FFI-Client for this.
