### ISSUE TITLE
Add scrollable openChatsList

### ISSUE THREAD

**Issue by rohansaw** [hpi-swa-teaching/TelegramClient#124]
**Is your feature request related to a problem? Please describe.**
The chatslist currently only shows as many chats as fit in the Main Window. But User should be able to scroll down and see all open chats. They are currently hidden because morph overflow is hidden.

**Describe the solution you'd like**
Build a Scrollable List. Maybe the Legacy Project hast this implemented?

**Comment by schmidtjonas** [comment]
Needs to have properly ordered list of chats first
