### ISSUE TITLE
Make chatsList ordered in clean way

### ISSUE THREAD

**Issue by rohansaw** [hpi-swa-teaching/TelegramClient#125]
**Is your feature request related to a problem? Please describe.**
Currently chats List is not ordered. This could be because, when we receive a new chat its order is always 0. Not sure if this should be this way. Could also be that this is expected behavior and we should also use chat-id to sort the chats List.

Please read both these links and source code example for a proper solution!

https://github.com/tdlib/td/issues/655

https://github.com/tdlib/td/blob/278c7acdec83c5ac17d8e1ed0bb2cacbcea62460/example/java/org/drinkless/tdlib/example/Example.java#L246

**Describe the solution you'd like**
Make sure that chats will be held in a ordered list.

**Comment by rohansaw** [comment]
Build this on base of feature/gh-123 as this belongs to refactoring chatsList.

**Comment by schmidtjonas** [comment]
To further order the existing chats, we need to handle more events from tdlib which tell us the updated chatorder

**Comment by rohansaw** [comment]
This was sold as a new User story -> closes #125
