### ISSUE TITLE
Display push notifications

### ISSUE THREAD

**Issue by Mrnikbobjeff** [hpi-swa-teaching/TelegramClient#16]
**Is your feature request related to a problem? Please describe.**
Received push notifications are ignored up until now.
**Describe the solution you'd like**
Received push notifications should be displayed as some sort of popup

**Describe alternatives you've considered**
None
**Additional context**
See any mobile phone push notification window
**Estimate:**
2 Pizzen

**Comment by Mrnikbobjeff** [comment]
This will be very complex as it requires OS interaction I believe

**Comment by rohansaw** [comment]
Could somebody add function that gets loggedIn User id directly after auth (maybe an update with loggedInUserID is sent automatically) otherwise please build a function to get it.
The loggedIn User id should be saved in TCCCore in loggedInUserID
