### ISSUE TITLE
Display a list of all available open chats

### ISSUE THREAD

**Issue by Mrnikbobjeff** [hpi-swa-teaching/TelegramClient#18]
**Is your feature request related to a problem? Please describe.**
Already present chats should be displayed in a listview to navigate to the masterdetail page of a singular chat.

**Describe the solution you'd like**
All currently active chats are displayed in a list

**Describe alternatives you've considered**
None really, messaging apps all have this list

**Additional context**
Listview items have to be bound to an id as to identify the correct messages to load
**Estimate:**
3 Pizzen

**Comment by Lasklu** [comment]
related to #65
