### ISSUE TITLE
Visualize sender of message

### ISSUE THREAD

**Issue by schmidtjonas** [hpi-swa-teaching/TelegramClient#189]
**Is your feature request related to a problem? Please describe.**
Every ingoing message looks the same, which make group chats hard to use.

**Describe the solution you'd like**
Feel free to think of your own solution. I could imagine different colors for different senders or displaying a name for every message. It also would be quite cool to wait for #24 and display a contact image to the left of a message.

To achieve this you would need to

- [ ] save some reference to a sender object in TCCMessage instead of just the sender id
- [ ] display this information in the initialization of TCUMessage

**Comment by schmidtjonas** [comment]
resolved by #253

**Comment by rohansaw** [comment]
Not really in group chats?

**Comment by schmidtjonas** [comment]
That is true, I'll edit the message
