### ISSUE TITLE
Clean up baseline

### ISSUE THREAD

**Issue by schmidtjonas** [hpi-swa-teaching/TelegramClient#193]
**Is your feature request related to a problem? Please describe.**
The baseline file is currently copy pasted and works but most of it is not needed and not self-explaining.

**Describe the solution you'd like**
Make sure which package has which dependencies and update them accordingly. Also remove unnecessary groups and packages.

**Comment by Mrnikbobjeff** [comment]
I do not know if it is possible to target a different .ston config on swalint, this could also improve the speed of the testing pipeline and reduce false negative runs due to timeout.
