### ISSUE TITLE
No CodeCoverage uploaded to Coveralls anymore

### ISSUE THREAD

**Issue by Lasklu** [hpi-swa-teaching/TelegramClient#199]
**Describe the bug**
The code coverage is not uploaded to [coveralls](https://coveralls.io/github/hpi-swa-teaching/TelegramClient)

**To Reproduce**
Look into the link above

**Expected behavior**
Upload of the code coverage at any PR

**Comment by rohansaw** [comment]
Will this be fixed until we have to submit the project or will we leave this open?

**Comment by Lasklu** [comment]
You can look into the PR and in [slack](https://hpi-swa-teaching.slack.com/archives/C0125EU8YE6/p1595415418007900)
Im in contact with Fabio Niephaus. It seems like unexpected behaviour from smalltalkCI.
Hopefully we can close this soon

**Comment by Lasklu** [comment]
solved. dc15c7f
