### ISSUE TITLE
Make message text readonly

### ISSUE THREAD

**Issue by Mrnikbobjeff** [hpi-swa-teaching/TelegramClient#210]
**Describe the bug**
We currently can edit the text inside of messages
**To Reproduce**
1. Go to a message
2. Click on ´the text
3. See error

**Expected behavior**
It should be like a label

**Screenshots**
![messagew](https://user-images.githubusercontent.com/6277666/88377743-04f75180-cda0-11ea-957b-86a33394bbd5.PNG)

**Comment by rohansaw** [comment]
Just add 'self lock' for the label that should fix it. (Bin grad nicht am rechner und kanns deswegen net machen)

**Comment by Mrnikbobjeff** [comment]
yes gerade auch getestet
