### ISSUE TITLE
rapidly hammernig a chat adds the last message several times to the chat

### ISSUE THREAD

**Issue by Mrnikbobjeff** [hpi-swa-teaching/TelegramClient#214]
**Describe the bug**
Chat messages are duplicated when repeatedly selecting and unselecting  the same chat in a short timeframe

**To Reproduce**
1. Go to the chat overview
2. Click on  any chat rapidly
3. See error

**Expected behavior**
Chats remain the same

**Screenshots**

![messsage existance](https://user-images.githubusercontent.com/6277666/88382419-af737280-cda8-11ea-9d69-74c78b467017.PNG)

**Comment by Mrnikbobjeff** [comment]
self mutex critical: ["code"] um den newChatSelected?

**Comment by rohansaw** [comment]
Bessere solution wäre vllt generell rauszufinden, dass wir nur einmal die alten messages vom server laden und die auch direkt in die Message liste kommen ohne den Chat mehrfach drücken zu müssen. Das sollte früher oder später eh geändert werden, das wir da nen cleaneres verhalten haben, also aufn chat drücken und entweder die alten nachichten wurden da schon gespeichert oder es wird nen call an den server gemacht der die nachrichten holt und sobal die nachrichten in squeak ankommen werden die automatisch in die chatmessage list eingefügt und die wird neu gerendert ohne dass man nochmal auf den chat klicken muss.

**Comment by schmidtjonas** [comment]
Branch 236 also doesn't seem to have this issue anymore, maybe I just can't reproduce it...

**Comment by rohansaw** [comment]
I also cant reproduce this error on current branch. I guess it was fixes as a side effect from chaning message loading logic
