### ISSUE TITLE
Add keyboard shortcuts for easier use

### ISSUE THREAD

**Issue by Mrnikbobjeff** [hpi-swa-teaching/TelegramClient#230]
**Is your feature request related to a problem? Please describe.**
ctrl->Enter should send a message, just like in web interface. also perhaps evaluate adding other keybindings

**Describe the solution you'd like**
Some actions such as pressing enter during auth or during message writing should perform actions. use  on: keyPattern send: aSelector to: aReceive - the usage is self eventHandler on: #(ctrl shift) -> Character arrowUp send: #pageUp to: self.

**Describe alternatives you've considered**
This is the way

**Comment by rohansaw** [comment]
Enter should already work for auth and message sending in current develop

**Comment by Mrnikbobjeff** [comment]
yep. only close and perhaps new chat should be bound

**Comment by rohansaw** [comment]
I just realised that it is not yet possible to have a linebreak inside the text. If user presses "shift + enter" he should be able to insert a newline in the text without directly sending it

**Comment by schmidtjonas** [comment]
Also I'd enjoy a Chat-switching shortcut like `Crtl + k`. It should work everywhere and focus a search field to search the name of the person to switch to. On `Enter` the Chat should be opened.
