### ISSUE TITLE
Add Unit tests

### ISSUE THREAD

**Issue by schmidtjonas** [hpi-swa-teaching/TelegramClient#235]
Unit tests are tests, that test single small units on their own. Please add a class in the tests package for every unit to be tested. Every class that implements some form of logic should have such a class.

**Comment by rohansaw** [comment]
Do unit tests really need to use test-dc? Can't we just test if calls to lib are properly made etc?

**Comment by Mrnikbobjeff** [comment]
test-dc?

**Comment by rohansaw** [comment]
Test Data-Center from Telegram
