### ISSUE TITLE
Long messages arent loaded

### ISSUE THREAD

**Issue by rohansaw** [hpi-swa-teaching/TelegramClient#237]
**Describe the bug**
If client recieves long text message (ca 1000 chars) it isnt loaded

**To Reproduce**
Send long message and open chat.

**Expected behavior**
Message should be displayed

**Additional context**
Maybe we timeout on loading?

**Comment by Mrnikbobjeff** [comment]
Can not reproduce, on fast internet connection and pc. perhaps slightly increase receive timeout?`
