### ISSUE TITLE
CI failing because of parallel execution

### ISSUE THREAD

**Issue by Lasklu** [hpi-swa-teaching/TelegramClient#243]
**Describe the bug**
Sometimes the CI fails and you have to restart it.

**To Reproduce**
Execute CI. The error behaviour only occurs sometimes

**Expected behavior**
A fluid CI which only fails if something is not correct

**Comment by Mrnikbobjeff** [comment]
As this was linked some commentary for posterity. We execute integration tests which will fail due to external dependencies when executede in parallel
