### ISSUE TITLE
Support setting your own profile picture for contacts

### ISSUE THREAD

**Issue by Mrnikbobjeff** [hpi-swa-teaching/TelegramClient#25]
**Is your feature request related to a problem? Please describe.**
Telegram clients support setting your contact picture. We also should support that via file selection.

**Describe the solution you'd like**
The user clicks on a button which opens a filechooser for image files. once the file has been verified to be a compatible image, we send it to the telegram server and sync our client.

**Describe alternatives you've considered**
Choosing via a camera etc could probably be suported, the amount of platform specific native code far outweighs the practicality

**Additional context**
We have not yet discussed this with our PO. Verify that this is wanted and needed

**Comment by rohansaw** [comment]
The Customer never requested this
