### ISSUE TITLE
Input Bar changes color

### ISSUE THREAD

**Issue by schmidtjonas** [hpi-swa-teaching/TelegramClient#252]
**Describe the bug**
The input bar changes from white to grey after first message in a chat

**To Reproduce**
Open a chat and send a message.

**Expected behavior**
It should stay white.

**Comment by rohansaw** [comment]
This is because i added a space before so that there is a character inside. Once the inputbar is empty it will turn grey and shrink

**Comment by schmidtjonas** [comment]
Seems unintended to me while using it. The background should be white all the time

**Comment by schmidtjonas** [comment]
Seems like there is no easy way to enforce a white background when the TextMorph is empty, so the white color will now be completely removed with #272 to make it look just like a normal TextMorph
