### ISSUE TITLE
Loading all chats on startup is slow and blocking other requests

### ISSUE THREAD

**Issue by rohansaw** [hpi-swa-teaching/TelegramClient#258]
**Describe the bug**
If Users has 300+ open Chats it takes a really long time to load/render them on startup. During this time all other calls to tdlib will be queued and user doesnt have any feedback

**To Reproduce**
Open TeleSqueak with lots of openchats

**Additional context**
TDlib is providing loading chatlimit and offset. maybe we can use this? I tried to change this, but the documentation states that offset is selected by library automaticcaly.

**Possible defects**
- Rerendering all the chatlist items every time a new chat is loaded -> Easy fix would be loading indicator
- It just takes a while to receive all this info from tdlib because it is polled only every 0.05s? But this shouldnt be a problem

**Comment by LinqLover** [comment]
May be related to #313. With the proposed patch, UI keeps responsive, but loading all chats still takes a few minutes, depending on the size of your Telegram account. A common pattern to overcome this might be to turn out rendering via an execution around method or a process-local variable.

**Comment by antonykamp** [comment]
see #531
