### ISSUE TITLE
edit README

### ISSUE THREAD

**Issue by Lasklu** [hpi-swa-teaching/TelegramClient#269]
polish our readme:

- [x] add feature table
- [x] improve setup guide
- [x] link our wiki
- [x] link other stuff
- [x] add codecoverage for master and dev (if fixed)
- [x] move unneccesary notes to wiki pages
- [x] decide on #275 and change if needed
- [x] polish readme like in smalltalkCI

**Comment by schmidtjonas** [comment]
Also move TDLib-Notes and possibly other sections to the wiki.

**Comment by rohansaw** [comment]
Also, Do we really want our discord server in the Repo?

**Comment by Lasklu** [comment]
I do not think so. There are no very important information for the next group..

**Comment by Lasklu** [comment]
> Also, Do we really want our discord server in the Repo?

Done.

**Comment by Lasklu** [comment]
Do we need codecoverage for master or dev in README? I could also add this like the CI-Badges @rohansaw @schmidtjonas

**Comment by rohansaw** [comment]
Please add coverage report for master and dev both in readme

**Comment by rohansaw** [comment]
Coverage is only for Core and not UI I guess?

**Comment by Lasklu** [comment]
https://github.com/hpi-swa-teaching/TelegramClient/blob/dc15c7f6835089accc4f32bdc356252140a6f7f5/.smalltalk.ston#L14

exactly

**Comment by Mrnikbobjeff** [comment]
Improved setup guide with correct FFI packages, this change was lost and the ticket was clsoed without fix
