### ISSUE TITLE
Do not limit CI on develop and master branch

### ISSUE THREAD

**Issue by Lasklu** [hpi-swa-teaching/TelegramClient#277]
**Describe the bug**
Up to now the CI is only executed on master and dev. We should make this avalaible (test -and linter CI) to every branch.

**Comment by Mrnikbobjeff** [comment]
no, definitely not. If you decide to create a pr the test will run. if you want to see wether you pass the tests execute them locally and start a pr. this way we dont flood the server with useless runs on every push which is not pr-ready

**Comment by Lasklu** [comment]
First of all: I forgot to link the closed PR ( #278 ) .
Hmmm. I have read an article from the one and only Martin Fowler and he recommends to build after each commit. 
[Link](https://martinfowler.com/articles/continuousIntegration.html#EveryoneCommitsToTheMainlineEveryDay)

A CI on every commit helps a lot to follow the TDD-pattern "Test very often". Furthermore you can detect & prevent bugs caused by the local machine of the developer. Everyone is after each commit encouraged to ensure that the tests will pass. If not he should fix this and we will have a much cleaner repo. Even on other branches. This is also crucial for our CodingStandards/Collective CodeOwnership. Another person has to be able to continue working on a feature started by another person without testing the code manually. A CI will generate more confidence for other developers.

Furthermore we do not contribute that a often to "flood" the server...

Whats the opinion of some other contributors?

**Comment by Mrnikbobjeff** [comment]
If you need that then the correct way of going about that is creating a draft pull request. The pipelines are executed. This way we dont have orphaned branches consuming resource. Especially if we had to pay for this this would be the correct solution. Also, consider builds where the build time is longer, i.e. Google Chrome. You would not be able to build one version before the next commit.
