### ISSUE TITLE
Trunk-Release after develop push fails

### ISSUE THREAD

**Issue by Lasklu** [hpi-swa-teaching/TelegramClient#281]
**Describe the bug**
The [CI](https://github.com/hpi-swa-teaching/TelegramClient/runs/948130184?check_suite_focus=true) throws an error while creating the release: "Published releases must have a valid tag". 

**To Reproduce**
1. Go to: [CI](https://github.com/hpi-swa-teaching/TelegramClient/runs/948130184?check_suite_focus=true)

**Comment by Mrnikbobjeff** [comment]
Fixed
