### ISSUE TITLE
Upgrade to tdlib-1.7.0

### ISSUE THREAD

**Issue by phkeese** [hpi-swa-teaching/TelegramClient#325]
Going to version 1.7.0 of tdlib allows us to order chats correctly.
“The user wants a fast development process. For that, documented apis are needed”

**Comment by tom-richter** [comment]
As far as I know we upgraded to 1.7 because we thought it might fix the broken pipeline. Ordering chats worked fine in 1.6. How to get a position of a chat changed in 1.7 and we have to update our app accordingly.
