### ISSUE TITLE
Number of chat members in header bar

### ISSUE THREAD

**Issue by jb3rndt** [hpi-swa-teaching/TelegramClient#342]
As a group member I want to see the number of people in a group in the header bar in order to know how many people I will reach with my messages.

**Comment by tom-richter** [comment]
Some Groups are BasicGroups and not Supergroups. For some reason getBasicGroupFullInfo returns none in python.

**Comment by tom-richter** [comment]
Is there an option to refresh the UI once the promise resolves?
