### ISSUE TITLE
Split tests into FFI Client Mock + Data Mock + API tests

### ISSUE THREAD

**Issue by tom-richter** [hpi-swa-teaching/TelegramClient#370]
+ Keep shared TD Core alive between tests to reduce annoyance of Test DC by large factor (-> Test resources, siehe Squeak By Example)
- includes #362

**Comment by rsommerfeld** [comment]
API Tests can use TestResources (see Squeak by Example) + Test Spy Pattern

**Comment by tom-richter** [comment]
#362
