### ISSUE TITLE
Codenachrichten im TelegramClient ausführen können

### ISSUE THREAD

**Issue by kohlros** [hpi-swa-teaching/TelegramClient#482]
Als Softwareentwickler nutze ich Telegram als Kommunikationskanal mit meinem Team, wobei häufig Code versendet wird. Um diesen möglichst schnell Testen und Anwenden zu können, möchte ich die Möglichkeit haben diesen direkt im TelegramClient ausführen zu lassen. 

Akzeptanzkriterium: Code in Nachrichten kann im TelegramClient genauso ausgeführt werden, als würde man ihn in den Workspace kopieren.

**Comment by antonykamp** [comment]
was implemented already
