### ISSUE TITLE
Profilbild taucht in der Kopfleiste auf

### ISSUE THREAD

**Issue by kohlros** [hpi-swa-teaching/TelegramClient#485]
Als Nutzer finde ich es angehnem wenn in der Kopfleiste das entsprechende Profilbild oder Placeholder angezeigt wird, um angenehmer erkennen zu können in welchem Chat ich mich gerade befinde. 

Akzeptanzkriterium: In allen Chats wird das Profilbild oben in der Chatleiste angezeigt.

**Comment by antonykamp** [comment]
not wanted anymore
