### ISSUE TITLE
Liste von nicht unterstützten NachrichtenTypen

### ISSUE THREAD

**Issue by jacob271** [hpi-swa-teaching/TelegramClient#493]
Als Kunde würde ich gerne wissen, welche Nachrichtentypen bereits unterstützt werden und welche noch fehlen, um so besser planen zu können, welche davon ich gerne umgesetzt sehen würde.

Akzeptanzkriterium: Es wurde eine solche Liste erstellt.

**Comment by kohlros** [comment]
## Not supported message Types: 

### Additional info is discarded (but message is still visible): 

- forwarded message
- was edited
- has protected content


### appears as "unsupported message": 
- audio
- documents
- animation 
- game 
- album
- sticker (already a user story)
- video
- voice
- video_note 
- contact 
- location (venue)
- pinned message
- polls
- bots
- voiceChat stuff 
- livelocation
- captions
- reactions

### information messages about the chat

- new chat members
- left chat member
- new chat title 
- new chat photo
- delete chat photo
- groupchat created
- channel created 
- voice chat 

### other things supported by Telegram 
- invoice
- successful payment
- signatures
- passport
- dice

Any features that were added in the recent "Telegram Premium" update are also not supported.
