### ISSUE TITLE
Chats schneller laden

### ISSUE THREAD

**Issue by jacob271** [hpi-swa-teaching/TelegramClient#495]
Als Telegram-Power User ist es mir wichtig einen Chat schnell auswählen und die Nachrichten sehen zu können. Aktuell dauert es jedes Mal, wenn ich einen Chat auswähle eine gewisse Zeit bis, alle Nachrichten zu sehen sind. Hier fände ich es angenehm, wenn dies schneller abläuft.

Akzeptanzkriterium: Im Normalfall werden direkt nach dem Klick auf einen Chat in der Chatliste die letzten Nachrichten angezeigt.

Edit: Ein Teil der Aufgabe besteht aus dem schneller Laden der Profilbilder.

**Comment by antonykamp** [comment]
see #531
