### ISSUE TITLE
Refactor TCUDayDividerMessage, TCUInfoMessage and TCUMessageWrapper

### ISSUE THREAD

**Issue by rgwohlbold** [hpi-swa-teaching/TelegramClient#528]
These messages are pretty similar, yet they do not share any superclass. Current code uses `isKindOf` to test for class membership, a definitive code smell.

Additionally, we get "Error: Object is not in collection" when clicking a reply to a TCUInfoMessage.

Also, when scrolling up, we sometimes get MessageNotUnderstood: RectangleMorph>>message since `self items first` can be a RectangleMorph instead of TCUMessageWrapper.

**Comment by jacob271** [comment]
completed with #529
