### ISSUE TITLE
Build UI for loggedIn User

### ISSUE THREAD

**Issue by rohansaw** [hpi-swa-teaching/TelegramClient#65]
**Is your feature request related to a problem? Please describe.**
The User need Visual Feedback once he is logged in. 

**Describe the solution you'd like**
Display a UI, where chats etc. will later be, which now only, displays a Welcome Message. Stay consistent with TelegramStyle.

**Describe alternatives you've considered**
Show welcome Message in Authscreen

**Comment by Lasklu** [comment]
related to #65
