### ISSUE TITLE
Client has to be Freed

### ISSUE THREAD

**Issue by rohansaw** [hpi-swa-teaching/TelegramClient#69]
**Describe the bug**
If client is left open in the Background and only the Morph is deleted, we will encounter an error that DB is already encripted, when trying to reopen a client.
**To Reproduce**
Create new TeleClient. 
Create another Teleclient -> Will receive error, that its already encripted

**Expected behavior**
If a Teleclient is already open, then we should use that Client, and not create a new one, or otherwise delete the old one.

**Comment by schmidtjonas** [comment]
Client is now freed by pr #102. DB is then decrypted/deleted by #79.
