### ISSUE TITLE
Missing Tests

### ISSUE THREAD

**Issue by schmidtjonas** [hpi-swa-teaching/TelegramClient#90]
**Describe the bug**
Tests are only testing the mock client. Specific Tests need to be added.

**Comment by Mrnikbobjeff** [comment]
We should not do that. Testing already tested functionality is wasted time. we can simply fake the return values of the actual fficlient. Not only that, but this would be hard to actually do as we would need to deploy the binaries to the smalltalkci squeak env, which Patrick said would be considerable work.

**Comment by schmidtjonas** [comment]
got it. I was worried the new FFIClient without module name was not working on other OSes besides mac
